HISTORY_STEPS = 11
FUTURE_STEPS = 80
CURRENT_STEP_INDEX = 10
TOTAL_STEPS = HISTORY_STEPS + FUTURE_STEPS

MAX_NEIGHBOUR_AGENTS = 32
MAX_MAP_POLYLINES = 128
POINTS_PER_POLYLINE = 20

NUM_PREDICTED_MODES = 6

PREDICTED_OBJECT_TYPES = ("TYPE_VEHICLE", "TYPE_PEDESTRIAN", "TYPE_CYCLIST")
NUM_OBJECT_TYPES = len(PREDICTED_OBJECT_TYPES)

MAP_POLYLINE_KINDS = (
    "lane",
    "road_line",
    "road_edge",
    "stop_sign",
    "crosswalk",
    "speed_bump",
    "driveway",
)
NUM_MAP_POLYLINE_KINDS = len(MAP_POLYLINE_KINDS)

AGENT_POSITION = slice(0, 2)
AGENT_HEADING_COSINE = 2
AGENT_HEADING_SINE = 3
AGENT_VELOCITY = slice(4, 6)
AGENT_EXTENT = slice(6, 8)
AGENT_TYPE = slice(8, 8 + NUM_OBJECT_TYPES)
AGENT_FEATURE_DIM = AGENT_TYPE.stop

MAP_POSITION = slice(0, 2)
MAP_DIRECTION = slice(2, 4)
MAP_KIND = slice(4, 4 + NUM_MAP_POLYLINE_KINDS)
MAP_FEATURE_DIM = MAP_KIND.stop

MISS_RATE_THRESHOLD_METRES = 2.0
EVALUATED_HORIZON_STEPS = (30, 50, 80)

OFFROAD_HORIZON_STEPS = 30
OFFROAD_DISTANCE_LIMIT_METRES = 1.65

SAMPLE_ARRAY_SPEC = {
    "agent_history": (HISTORY_STEPS, AGENT_FEATURE_DIM),
    "agent_history_mask": (HISTORY_STEPS,),
    "neighbour_history": (MAX_NEIGHBOUR_AGENTS, HISTORY_STEPS, AGENT_FEATURE_DIM),
    "neighbour_history_mask": (MAX_NEIGHBOUR_AGENTS, HISTORY_STEPS),
    "map_polylines": (MAX_MAP_POLYLINES, POINTS_PER_POLYLINE, MAP_FEATURE_DIM),
    "map_polylines_mask": (MAX_MAP_POLYLINES, POINTS_PER_POLYLINE),
    "future_positions": (FUTURE_STEPS, 2),
    "future_mask": (FUTURE_STEPS,),
    "frame_origin": (2,),
    "frame_heading": (),
}
